defaults:
  - _self_
  - eval_env: pusht
  - env_vars: env_vars

# Model (VLA-Adapter)
model_family: "openvla"
pretrained_checkpoint: ""  # Path to fine-tuned checkpoint dir (…--<step>_chkpt)
use_l1_regression: true
use_diffusion: false
use_minivlm: true
use_pro_version: true
save_version: "vla-adapter"
phase: "Inference"
num_diffusion_steps_train: 50
num_diffusion_steps_inference: 50
use_film: false
use_proprio: false
center_crop: true
lora_rank: 64
load_in_8bit: false
load_in_4bit: false

# Environment (overridden by eval_env configs)
env_name: ${eval_env.env_name}
num_images_in_input: ${eval_env.num_images_in_input}
num_open_loop_steps: ${eval_env.num_open_loop_steps}
num_trials: 100
max_steps: 300
num_steps_wait: ${eval_env.num_steps_wait}
cube_env_type: "double"  # Only used for cube env
cube_task_id: 5          # Only used for cube env: task5_stack

# Action (overridden by eval_env configs)
action_dim: ${eval_env.action_dim}
num_actions_chunk: ${eval_env.num_actions_chunk}
proprio_dim: ${eval_env.proprio_dim}
normalization_type: ${eval_env.normalization_type}
unnorm_key: ""

# Logging
run_id_note: null
local_log_dir: ${env_vars.run_root_dir}/eval_logs
save_videos: true
video_fps: 10
use_wandb: true
wandb_entity: ${env_vars.wandb_entity}
wandb_project: ${env_vars.wandb_project}
seed: 7

hydra:
  job:
    chdir: false
  run:
    dir: ${env_vars.run_root_dir}/hydra_eval/${now:%Y-%m-%d}/${now:%H-%M-%S}
